name: First Workflow

on: workflow_dispatch

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: | 
          apt install
          echo "I've reloaded the system sucessfully!"
      - name: Print goodbye
        run: |
          echo "The content of directory"
          ls -la
          echo "Done - bye!"
