name: Test Project

on: push

jobs:
  test:
    uses: ./.github/workflows/template.yml
    with:
      run-command: 'npm test'
  build:
    uses: ./.github/workflows/template.yml
    needs: test
    with:
      run-command: 'npm run build'
  deploy:
    uses: ./.github/workflows/template.yml
    needs: build
    with:
      run-command: 'npm run build'
      deploy-command: 'echo "Deploying ..."'