name: First Workflow

on: workflow_dispatch

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: | 
          echo "Checking content of dir"
          ls -la
          touch secret-file.txt
          ls -la
          echo "Checking was donea"
      - name: Print goodbye
        run: |
          echo "The content of directory"
          ls -la
          echo "Done - bye!"
